### ISSUE TITLE
App crashes when solved.

### ISSUE THREAD

**Issue by cmsteffen-code** [steve-shambles/Bletchley#3]
If I solve the puzzle and click submit, the app congratulates me, then closes with the following error:

    Exception in Tkinter callback
    Traceback (most recent call last):
      File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
        return self.func(*args)
      File "bletchley-v1-083.py", line 300, in decode_row1
        LAB1 = Label(FRAME1, bg="yellow", text=shuffled)
      File "/usr/lib/python3.7/tkinter/__init__.py", line 2766, in __init__
        Widget.__init__(self, master, 'label', cnf, kw)
      File "/usr/lib/python3.7/tkinter/__init__.py", line 2299, in __init__
        (widgetName, self._w) + extra + self._options(cnf))
    _tkinter.TclError: can't invoke "label" command: application has been destroyed

This seems to be caused by the application attempting to fill in the yellow box next to my attempt, despite the app window having already been closed.

**Comment by cmsteffen-code** [comment]
Did I? I didn’t realize it. Last I checked it still crashed with the error message! I’ll look at it again when I can get back online.

**Comment by cmsteffen-code** [comment]
Yeah this will come out in the wash. Like I said, it’s likely because it’s trying to check fields on a window that’s been deconstructed.
